services:
  privaxy:
    image: ghcr.io/joshrmcdaniel/privaxy
    ports:
      - "8100:8100"
      - "8200:8200"
    volumes:
      - ./conf:/conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
